// Generated by https://quicktype.io

export interface CovidNew {
  articles: Article[]
}

export interface Article {
  summary: string
  country: Country
  author: string
  link: string
  media: string
  title: string
  media_content: string[]
  clean_url: string
  published_date: string
}

export enum Country {
  MX = 'MX',
}

export enum Lang {
  Es = 'es',
}

export enum Topic {
  Economics = 'economics',
  News = 'news',
  Science = 'science',
  World = 'world',
}
